/*
 *Copyright (C) 2024 Intel Corporation
 * 
 *Licensed under the Apache License, Version 2.0 (the "License");
 *you may not use this file except in compliance with the License.
 *You may obtain a copy of the License at
 * 
 *http://www.apache.org/licenses/LICENSE-2.0
 * 
 *Unless required by applicable law or agreed to in writing,
 *software distributed under the License is distributed on an "AS IS" BASIS,
 *WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *See the License for the specific language governing permissions
 *and limitations under the License.
 * 
 *
 *SPDX-License-Identifier: Apache-2.0
*/
#include "ippi_l.h"

#ifndef NULL
#ifdef  __cplusplus
#define NULL    0
#else
#define NULL    ((void *)0)
#endif
#endif

void ippi_lTest()
{
	IppStatus status;
	IppiSize ippiSize= {0,0};
	IppiPoint ippiPoint= {0,0};
	IppiPoint_32f ippiPoint_32f= {0.0f,0.0f};
	IppPointPolar ippPointPolar= {0.0f,0.0f};
	IppiRect ippiRect= {0,0,0,0};
	IpprVolume ipprVolume= {0, 0, 0};
	IpprCuboid ipprCuboid= {0,0,0,0,0,0};
	IpprPoint ipprPoint= {0,0,0};
	Ipp16sc ipp16sc= {0,0};
	Ipp32sc ipp32sc= {0,0};
	Ipp32fc ipp32fc= {0.0f,0.0f};
	Ipp64sc ipp64sc= {0.0f,0.0f};
	Ipp64fc ipp64fc= {0.0f,0.0f};
	IppSizeL ippSizeL = {0};
	IppiSizeL ippiSizeL = {0,0};
	IppiPointL ippiPointL = {0,0};
	IppiRectL ippiRectL = {0,0,0,0};
	IpprVolumeL ipprVolumeL = {0,0,0};
	IpprBorderType ipprBorderType = 0;

	ippiMalloc_8u_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16u_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16s_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32s_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32f_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32sc_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32fc_C1_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_8u_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16u_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16s_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32s_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32f_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32sc_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32fc_C2_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_8u_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16u_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16s_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32s_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32f_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32sc_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32fc_C3_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_8u_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16u_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16s_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32s_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32f_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32sc_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32fc_C4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_8u_AC4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16u_AC4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_16s_AC4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32s_AC4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32f_AC4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32sc_AC4_L(ippSizeL, ippSizeL, NULL);
	ippiMalloc_32fc_AC4_L(ippSizeL, ippSizeL, NULL);
	status = ippiCopy_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_8u_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16s_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_16u_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32s_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopy_32f_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiCopyReplicateBorder_8u_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32s_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_32f_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_8u_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16u_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyReplicateBorder_16s_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyWrapBorder_32s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyWrapBorder_32s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyWrapBorder_32f_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyWrapBorder_32f_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyConstBorder_8u_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_8u_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_8u_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_8u_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_16s_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16s_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16s_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_32s_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32s_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32s_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16u_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_16u_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16u_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16u_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32f_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, 0.0f);
	status = ippiCopyConstBorder_32f_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32f_AC4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32f_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_8u_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_8u_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_8u_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_8u_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16u_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_16u_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16u_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16u_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_16s_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16s_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_16s_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, 0);
	status = ippiCopyConstBorder_32s_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32s_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32s_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32f_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, 0.0f);
	status = ippiCopyConstBorder_32f_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32f_AC4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyConstBorder_32f_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL, NULL);
	status = ippiCopyMirrorBorder_8u_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_8u_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_8u_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16s_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16s_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32s_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32s_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32s_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_8u_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_8u_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_8u_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16s_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16s_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32s_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32s_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32s_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16u_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16u_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16u_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16u_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16u_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_16u_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32f_C1R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32f_C3R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32f_C4R_L(NULL, ippSizeL, ippiSizeL, NULL, ippSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32f_C1IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32f_C3IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiCopyMirrorBorder_32f_C4IR_L(NULL, ippSizeL, ippiSizeL, ippiSizeL, ippSizeL, ippSizeL);
	status = ippiAdd_8u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_8u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_8u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_8u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_8u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16s_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_16u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_C1IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_C3IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_C4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiSub_32f_AC4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_C1IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_C3IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_C4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_32f_AC4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_8u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_8u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMulC_16s_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiMul_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_C1IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_C3IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_C4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiMul_32f_AC4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_AC4R_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_C1IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_C3IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_C4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_32f_AC4IR_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_16s_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16s_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16s_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16s_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_C1RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_C3RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_C4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_AC4RSfs_L(NULL, ippSizeL, NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16s_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_8u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_16u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDivC_32f_C1R_L(NULL, ippSizeL, 0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_C3R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_C4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_AC4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_C1IR_L(0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_C3IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_C4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiDivC_32f_AC4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiDiv_16s_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16s_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16s_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16s_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_8u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiDiv_16u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_32f_C1R_L(NULL, ippSizeL, 0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_C3R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_C4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_AC4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_C1R_L(NULL, ippSizeL, 0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_C3R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_C4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_AC4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_C1R_L(NULL, ippSizeL, 0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_C3R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_C4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_AC4R_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_C1IR_L(0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_C3IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_C4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiAddC_32f_AC4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_C1IR_L(0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_C3IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_C4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiSubC_32f_AC4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_C1IR_L(0.0f, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_C3IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_C4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiMulC_32f_AC4IR_L(NULL, NULL, ippSizeL, ippiSizeL);
	status = ippiAdd_8u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_8u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_8u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_8u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16s_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAdd_16u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_8u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16s_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_C1IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_C3IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_C4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSub_16u_AC4IRSfs_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_C1RSfs_L(NULL, ippSizeL, 0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_C3RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_C4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_AC4RSfs_L(NULL, ippSizeL, NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_8u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16s_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiAddC_16u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_8u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16s_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_C1IRSfs_L(0, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_C3IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_C4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiSubC_16u_AC4IRSfs_L(NULL, NULL, ippSizeL, ippiSizeL, 0);
	status = ippiFilterBilateralBorderGetBufferSize_L(ippiFilterBilateralGauss, ippiSizeL, 0, ippUndef, 0, ippDistNormL1, NULL, NULL);
	status = ippiFilterBilateralBorderInit_L(ippiFilterBilateralGauss, ippiSizeL, 0, ippUndef, 0, ippDistNormL1, 0.0f, 0.0f, NULL);
	status = ippiFilterBilateralBorder_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateralBorder_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeGetSize_L(ippiSizeL, ippiSizeL, ippUndef, ippHahn, 0, NULL, NULL);
	status = ippiResizeGetBufferSize_L(NULL, ippiSizeL, 0, NULL);
	status = ippiResizeGetBorderSize_L(NULL, NULL);
	status = ippiResizeGetSrcOffset_L(NULL, ippiPointL, NULL);
	status = ippiResizeGetSrcRoi_L(NULL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearestInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL);
	status = ippiResizeLinearInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL);
	status = ippiResizeCubicInit_L(ippiSizeL, ippiSizeL, ippUndef, 0.0f, 0.0f, NULL, NULL);
	status = ippiResizeLanczosInit_L(ippiSizeL, ippiSizeL, ippUndef, 0, NULL, NULL);
	status = ippiResizeSuperInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL);
	status = ippiResizeLinearInit_8u_L(ippiSizeL, ippiSizeL, ippAlgHintNone, NULL);
	status = ippiResizeCubicInit_8u_L(ippiSizeL, ippiSizeL, 0.0f, 0.0f, ippAlgHintNone, NULL, NULL);
	status = ippiResizeLanczosInit_8u_L(ippiSizeL, ippiSizeL, 0, ippAlgHintNone, NULL, NULL);
	status = ippiResizeNearest_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeNearest_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeLinear_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_64f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_64f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLinear_64f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeCubic_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeLanczos_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeSuper_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeSuper_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiResizeAntialiasingLinearInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL, NULL);
	status = ippiResizeAntialiasingCubicInit_L(ippiSizeL, ippiSizeL, ippUndef, 0.0f, 0.0f, NULL, NULL);
	status = ippiResizeAntialiasingLanczosInit_L(ippiSizeL, ippiSizeL, ippUndef, 0, NULL, NULL);
	status = ippiResizeAntialiasing_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiResizeAntialiasing_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiWarpGetBufferSize_L(NULL, ippiSizeL, NULL);
	status = ippiGetAffineBound_L(ippiRectL, NULL, NULL);
	status = ippiGetAffineQuad_L(ippiRectL, NULL, NULL);
	status = ippiGetAffineTransform_L(ippiRectL, NULL, NULL);
	status = ippiGetAffineSrcRoi_L(ippiSizeL, NULL, ippWarpForward, ippiPointL, ippiSizeL, NULL);
	status = ippiGetRotateShift_L(0.0f, 0.0f, 0.0f, NULL, NULL);
	status = ippiGetRotateTransform_L(0.0f, 0.0f, 0.0f, NULL);
	status = ippiWarpAffineGetSize_L(ippiSizeL, ippiSizeL, ippUndef, NULL, ippHahn, ippWarpForward, ippBorderConst, 0, NULL, NULL);
	status = ippiWarpAffineNearestInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL, ippWarpForward, 0, ippBorderConst, NULL, 0, NULL);
	status = ippiWarpAffineLinearInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL, ippWarpForward, 0, ippBorderConst, NULL, 0, NULL);
	status = ippiWarpAffineCubicInit_L(ippiSizeL, ippiSizeL, ippUndef, NULL, ippWarpForward, 0, 0.0f, 0.0f, ippBorderConst, NULL, 0, NULL, NULL);
	status = ippiWarpAffineNearest_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_64f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_64f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineNearest_64f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_64f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_64f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineLinear_64f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_8u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_16u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_16u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_16u_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_16s_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_16s_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_16s_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_32f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_64f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_64f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ippiWarpAffineCubic_64f_C4R_L(NULL, ippSizeL, NULL, ippSizeL, ippiPointL, ippiSizeL, NULL, NULL);
	status = ipprFilterBorderGetSize_L(ipprVolumeL, ipprVolumeL, ippUndef, ippUndef, 0, NULL, NULL);
	status = ipprFilterBorderInit_16s_L(NULL, ipprVolumeL, 0, ippUndef, 0, NULL);
	status = ipprFilterBorderInit_32f_L(NULL, ipprVolumeL, ippUndef, 0, NULL);
	status = ipprFilterBorderInit_64f_L(NULL, ipprVolumeL, ippUndef, 0, NULL);
	status = ipprFilterBorder_8u_C1V_L(NULL, ippSizeL, ippSizeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ipprBorderType, NULL, NULL, NULL);
	status = ipprFilterBorder_16s_C1V_L(NULL, ippSizeL, ippSizeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ipprBorderType, NULL, NULL, NULL);
	status = ipprFilterBorder_16u_C1V_L(NULL, ippSizeL, ippSizeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ipprBorderType, NULL, NULL, NULL);
	status = ipprFilterBorder_32f_C1V_L(NULL, ippSizeL, ippSizeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ipprBorderType, NULL, NULL, NULL);
	status = ipprFilterBorder_64f_C1V_L(NULL, ippSizeL, ippSizeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ipprBorderType, NULL, NULL, NULL);
	status = ipprCopyConstBorder_8u_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL, NULL);
	status = ipprCopyConstBorder_16u_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL, NULL);
	status = ipprCopyConstBorder_16s_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL, NULL);
	status = ipprCopyConstBorder_32f_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL, NULL);
	status = ipprCopyConstBorder_64f_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL, NULL);
	status = ipprCopyReplicateBorder_8u_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL);
	status = ipprCopyReplicateBorder_16u_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL);
	status = ipprCopyReplicateBorder_16s_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL);
	status = ipprCopyReplicateBorder_32f_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL);
	status = ipprCopyReplicateBorder_64f_C1V_L(NULL, ippSizeL, ippSizeL, ipprVolumeL, NULL, ippSizeL, ippSizeL, ipprVolumeL, ippSizeL, ippSizeL, ippSizeL);
	status = ippiFilterBilateralGetBufferSize_L(ippiFilterBilateralGauss, ippiSizeL, ippSizeL, ippUndef, 0, ippDistNormL1, NULL, NULL);
	status = ippiFilterBilateralInit_L(ippiFilterBilateralGauss, ippiSizeL, ippSizeL, ippUndef, 0, ippDistNormL1, 0.0f, 0.0f, NULL);
	status = ippiFilterBilateral_8u_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_8u_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_32f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_32f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_64f_C1R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_64f_C3R_L(NULL, ippSizeL, NULL, ippSizeL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_8u_P3R_L(NULL, NULL, NULL, NULL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_32f_P3R_L(NULL, NULL, NULL, NULL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);
	status = ippiFilterBilateral_64f_P3R_L(NULL, NULL, NULL, NULL, ippiSizeL, ippBorderConst, NULL, NULL, NULL);

}
